import {
  ArrowLeftRight,
  Banknote,
  BanknoteArrowUp,
  Bell,
  Check,
  ChevronDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CreditCard,
  Eye,
  EyeOff,
  Info,
  LayoutGrid,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MessageCircleMore,
  Moon,
  Percent,
  PiggyBank,
  Search,
  Settings,
  Sun,
  TriangleAlert,
  User,
  UserRound,
  WalletCards,
  X,
} from 'lucide-react';

export const icons = {
  eye: Eye,
  'eye-off': EyeOff,
  mail: Mail,
  lock: Lock,
  user: User,
  'user-round': UserRound,
  sun: Sun,
  moon: Moon,
  check: Check,
  'circle-check-big': CircleCheckBig,
  x: X,
  info: Info,
  'circle-alert': CircleAlert,
  'triangle-alert': TriangleAlert,
  'loader-circle': LoaderCircle,
  'layout-grid': LayoutGrid,
  'credit-card': CreditCard,
  'arrow-left-right': ArrowLeftRight,
  'wallet-cards': WalletCards,
  'piggy-bank': PiggyBank,
  percent: Percent,
  'banknote-arrow-up': BanknoteArrowUp,
  settings: Settings,
  'chevrons-right': ChevronsRight,
  'chevrons-left': ChevronsLeft,
  search: Search,
  bell: Bell,
  'message-circle-more': MessageCircleMore,
  'log-out': LogOut,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  banknote: Banknote,
} as const;
