import {
  Apple,
  ArrowLeftRight,
  ArrowUp,
  Banknote,
  BanknoteArrowDown,
  BanknoteArrowUp,
  Bell,
  BookOpenText,
  Briefcase,
  Car,
  CarTaxiFront,
  Cat,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  Clapperboard,
  CreditCard,
  Drill,
  Droplet,
  Ellipsis,
  Eye,
  EyeOff,
  Flower,
  Gamepad2,
  Globe,
  HandCoins,
  HandHeart,
  Heart,
  House,
  Info,
  Landmark,
  LayoutGrid,
  Loader,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  MessageCircleMore,
  Moon,
  Percent,
  PiggyBank,
  Plus,
  Scissors,
  Search,
  Settings,
  Shirt,
  Smartphone,
  Sun,
  TriangleAlert,
  Trophy,
  Truck,
  Umbrella,
  User,
  UserRound,
  Utensils,
  Volleyball,
  WalletCards,
  WashingMachine,
  X,
  Zap,
} from 'lucide-react';

export const icons = {
  eye: Eye,
  'eye-off': EyeOff,
  mail: Mail,
  lock: Lock,
  user: User,
  'user-round': UserRound,
  sun: Sun,
  moon: Moon,
  check: Check,
  'circle-check-big': CircleCheckBig,
  x: X,
  info: Info,
  'circle-alert': CircleAlert,
  'triangle-alert': TriangleAlert,
  'loader-circle': LoaderCircle,
  'layout-grid': LayoutGrid,
  'credit-card': CreditCard,
  'arrow-left-right': ArrowLeftRight,
  'wallet-cards': WalletCards,
  'piggy-bank': PiggyBank,
  percent: Percent,
  'banknote-arrow-up': BanknoteArrowUp,
  settings: Settings,
  'chevrons-right': ChevronsRight,
  'chevrons-left': ChevronsLeft,
  search: Search,
  bell: Bell,
  megaphone: Megaphone,
  'message-circle-more': MessageCircleMore,
  'log-out': LogOut,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'washing-machine': WashingMachine,
  'book-open-text': BookOpenText,
  utensils: Utensils,
  shirt: Shirt,
  truck: Truck,
  'hand-heart': HandHeart,
  'gamepad-2': Gamepad2,
  flower: Flower,
  apple: Apple,
  heart: Heart,
  umbrella: Umbrella,
  landmark: Landmark,
  'car-taxi-front': CarTaxiFront,
  briefcase: Briefcase,
  volleyball: Volleyball,
  drill: Drill,
  cat: Cat,
  clapperboard: Clapperboard,
  smartphone: Smartphone,
  ellipsis: Ellipsis,
  banknote: Banknote,
  'banknote-arrow-down': BanknoteArrowDown,
  scissors: Scissors,
  car: Car,
  house: House,
  globe: Globe,
  droplet: Droplet,
  zap: Zap,
  trophy: Trophy,
  'chart-line': ChartLine,
  plus: Plus,
  'hand-coins': HandCoins,
  'arrow-up': ArrowUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  loader: Loader,
} as const;
